### ISSUE TITLE
i'm gonna cum~

### ISSUE THREAD

**Issue by GordonFeetman** [vanssx3/emoji-cipher#3]
i'm so close but mommy won't help me :(

**Comment by GordonFeetman** [comment]
haiiiii maya ^w^

**Comment by GordonFeetman** [comment]
also hiii vanessa :3

**Comment by vanssx3** [comment]
😴🔥🥳🤡😣🤡🔥🤯😣🍉🥳😭🥶😣🥳🐱😣😡😮👶😮😈👽😣😭😦🤩🤯😴
i encrypted this btw :3333

**Comment by GordonFeetman** [comment]
lemme decrypt this rq
